Repository JapaneseEducateService/backend-python, pull requests merged in 2024-04, with the labels that each got.

#5 Update issue templates
  .github/ISSUE_TEMPLATE/✨-feature.md
Labels: ⚙ Setting

#7 🔨 Refactor : 디자인 패턴 변경, ✨ feat : 발음평가 Azure API 요청 구현
  app/__init__.py
  app/apis/__init__.py
  app/apis/morpheme.py
  app/apis/speech.py
  app/app.py
  app/core/__init__.py
  app/core/pronunciation_assessment.py
  app/core/speechTest.py
  app/requirements.txt
  app/speech.py
  docker-compose.yml
  dockerfile
Labels: ✨ Feature, 🔨 Refactor

#8 🔨 Refactor : docker설정 변경
  app/__init__.py
  app/apis/__init__.py
  app/apis/morpheme.py
  app/apis/speech.py
  app/app.py
  app/core/__init__.py
  app/core/pronunciation_assessment.py
  app/core/speechTest.py
  app/requirements.txt
  docker-compose.yml
  dockerfile
Labels: 🔨 Refactor

#9 🔨 Refactor : docker설정 변경
  app/apis/morpheme.py
  app/apis/speech.py
  app/app.py
  app/core/pronunciation_assessment.py
  app/core/speechTest.py
  docker-compose.yml
Labels: 🔨 Refactor

#11 ✨ feat : 발음평가 구현
  .gitignore
  app/apis/speech.py
  app/app.py
  app/core/google_text_to_speech.py
  app/core/pitch_comparison.py
  app/core/pronunciation_assessment.py
  app/requirements.txt
Labels: ✨ Feature

#12 Create main.yml
  .github/workflows/main.yml
Labels: 🌏 Deploy, ✅ Test

#14 ✨ feat : GoogleTTS 구현
  app/apis/speech.py
  app/core/pitch_comparison.py
Labels: ✨ Feature

#15 🔨 Refactor : 오디오 파일 청크로 쪼개지 않고 전송
  app/audio/テスト.wav
  app/core/pronunciation_assessment.py
Labels: 🔨 Refactor

#17 🐞 BugFix : 오디오 파일 청크로 쪼개지 않고 전송(점수 에러)
  app/apis/speech.py
  app/core/pitch_comparison.py
  app/core/pronunciation_assessment.py
Labels: 🐞 BugFix
