Repository JapaneseEducateService/backend-python, pull requests merged in 2024-05, with the labels that each got.

#19 🔨 Refactor : flask 배포용 수정
  app/core/pronunciation_assessment.py
  dockerfile
  start.sh
Labels: 🔨 Refactor

#20 🌏 Deploy : flask 배포
  app/core/pronunciation_assessment.py
  dockerfile
  start.sh
Labels: 🌏 Deploy

#22 🌏 Deploy : flask 배포용 수정
  dockerfile
  start.sh
Labels: 🌏 Deploy

#23 🌏 Deploy : flask 배포용 수정
  start.sh
Labels: 🌏 Deploy

#24 🌏 Deploy : release v1.0.0
  dockerfile
  start.sh
Labels: 🌏 Deploy

#25 🐞 BugFix : 잘못된 값 반환 오류 수정
  app/apis/__init__.py
  app/apis/morpheme.py
  app/apis/speech.py
  app/app.py
  app/core/pronunciation_assessment.py
Labels: 🐞 BugFix

#28 🐞 BugFix : 스웨거 작성 오류 수정
  app/apis/morpheme.py
  dockerfile
Labels: 🐞 BugFix

#29 🐞 BugFix : 스웨거 작성 오류 수정 , 🌏 Deploy: main release 1.0.3
  app/apis/morpheme.py
  dockerfile
Labels: 🐞 BugFix, 🌏 Deploy
